apiVersion: v1
kind: Pod
metadata:
  name: sql
  labels:
    app: sql
spec:
  containers:
  - name: sql-cont
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_DATABASE
      value: admin

    ports:
    - containerPort: 3306
      name: mysql
